url: "https://www.dotenv.org" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "Dotenv" # the name of your site, e.g. ACME Corp.
logo: "https://raw.githubusercontent.com/motdotla/dotenv/master/dotenv.svg"
description: "Simplify your secrets"

# Change assets path - https://github.com/envygeeks/jekyll-assets/issues/161
assets:
  sources:
    - assets-www

# Footer "Edit this page on GitHub" link text
github_edit_link: true # show or hide edit this page link
github_edit_link_text: "View on GitHub"
github_edit_repository: "https://github.com/dotenv-org/dotenv-org.github.io" # the github URL for your repo
github_edit_branch: "master" # the branch that your docs is served from
github_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# For SEO Jekyll Plugin
author:
  name: Dotenv
  twitter: dotenvorg
twitter:
  username: dotenvorg
  card: summary
social:
  name: Dotenv
  links:
    - https://twitter.com/dotenvorg
    - https://github.com/dotenv-org
    - https://linkedin.com/company/dotenvorg
    - https://www.youtube.com/@dotenvorg

defaults:
  - scope:
      path: ""
    values:
      image: "https://res.cloudinary.com/dotenv-org/image/upload/v1666566686/og-image_g0llrh.png"

# For Favicon Plugin
favicon:
  source: "favicon.png"

# Exclude files
exclude:
  - .DS_Store
  - README.md

markdown: kramdown
kramdown:
  highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

plugins:
  - jekyll-redirect-from
  - liquid_pluralize
  - liquid_reading_time
  - jekyll-timeago
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-favicon
  - jekyll-feed
  - jemoji

plugins_dir: ./_local_plugins
